let featuredProductsDB =[
  {
    id: 10,
    type: "shoes",
    imgUrl: "./assets/products/shoe1-1.jpg",
    imgUrl2: "./assets/products/shoe1-2.jpg",
    imgUrl3: "./assets/products/shoe1-3.jpg",
    imgUrl4: "./assets/products/shoe1.jpg",
    title: "Men Slip On Shoes Casual With Arch Support Insoles",
    reviewsCount: 2.548,
    price: 159.99,
    priceDashed: 199.98,
    Sold: 275,
    color: {
      color1: "red",
      color2: "green",
      color3: "blue",
    },
    size: {
      size1: 40,
      size2: 42,
      size3: 43,
      size4: 44,
    },
    information: {
      BRAND: "Nike",
      ACTIVITY: "Running",
      MATERIAL: "Fleece",
      GENDER: "Men",
    },
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ullam perspiciatis illum excepturi repudiandae aperiam incidunt.",
    custom: {
      size1: "XS",
      size2: "S",
      size3: "M",
      size4: "L",
      size5: "XL",
    },
    reviews: {
      stars: 4.9,
    },
    qty:0,
  },
  {
    id: 11,
    type: "apparel",
    imgUrl: "./assets/products/apparel1.jpg",
    imgUrl2: "./assets/products/apparel2.jpg",
    imgUrl3: "./assets/products/apparel3.jpg",
    imgUrl4: "./assets/products/apparel4.jpg",
    title: "Coat for men",
    reviewsCount: 354,
    price: 350.99,
    priceDashed: 400.98,
    Sold: 550,
    color: {
      color1: "red",
      color2: "green",
      color3: "blue",
    },
    size: {
      size1: "XS",
      size2: "S",
      size3: "M",
      size4: "XL",
    },
    information: {
      BRAND: "Zara",
      ACTIVITY: "Home",
      MATERIAL: "Cotton",
      GENDER: "Men",
    },
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ullam perspiciatis illum excepturi repudiandae aperiam incidunt.",
    custom: {
      size1: "XS",
      size2: "S",
      size3: "M",
      size4: "L",
      size5: "XL",
    },
    reviews: {
      stars: 4.9,
    },
    qty:0,
    
  },
  {
    id: 12,
    type:"electronic1",
    imgUrl: "./assets/products/electronic1.jpg",
    imgUrl2: "./assets/products/electronic2.jpg",
    imgUrl3: "./assets/products/electronic3.jpg",
    imgUrl4: "./assets/products/electronic4.jpg",
    title: "electronic",
    reviewsCount: 2.5,
    price: 290.99,
    priceDashed: 300.98,
    Sold: 250,
    color: {
      color1: "red",
      color2: "green",
      color3: "blue",
    },
    size: {
      size1: "XS",
      size2: "S",
      size3: "M",
      size4: "XL",
    },
    information: {
      BRAND: "Zara",
      ACTIVITY: "Home",
      MATERIAL: "Cotton",
      GENDER: "Women",
    },
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ullam perspiciatis illum excepturi repudiandae aperiam incidunt.",
    custom: {
      size1: "XS",
      size2: "S",
      size3: "M",
      size4: "L",
      size5: "XL",
    },
    reviews: {
      stars: 4.8,
    },
    qty:0,
  },
  {
    id: 13,
    type: "home",
    imgUrl: "./assets/products/home1.jpg",
    imgUrl2: "./assets/products/home2.jpg",
    imgUrl3: "./assets/products/home3.jpg",
    imgUrl4: "./assets/products/home4.jpg",
    title: "home",
    reviewsCount: 2.5,
    price: 290.99,
    priceDashed: 300.98,
    Sold: 250,
    color: {
      color1: "red",
      color2: "green",
      color3: "blue",
    },
    size: {
      size1: "XS",
      size2: "S",
      size3: "M",
      size4: "XL",
    },
    information: {
      BRAND: "Zara",
      ACTIVITY: "Home",
      MATERIAL: "Cotton",
      GENDER: "Women",
    },
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ullam perspiciatis illum excepturi repudiandae aperiam incidunt.",
    custom: {
      size1: "XS",
      size2: "S",
      size3: "M",
      size4: "L",
      size5: "XL",
    },
    reviews: {
      stars: 4.8,
    },
    qty:0,
  },
  {
    id: 14,
    type: "home",
    imgUrl: "./assets/banner/banner2.jpg",
    imgUrl2: "./assets/products/home2.jpg",
    imgUrl3: "./assets/products/home3.jpg",
    imgUrl4: "./assets/products/home4.jpg",
    title: "home",
    reviewsCount: 2.5,
    price: 290.99,
    priceDashed: 300.98,
    Sold: 250,
    color: {
      color1: "red",
      color2: "green",
      color3: "blue",
    },
    size: {
      size1: "XS",
      size2: "S",
      size3: "M",
      size4: "XL",
    },
    information: {
      BRAND: "Zara",
      ACTIVITY: "Home",
      MATERIAL: "Cotton",
      GENDER: "Women",
    },
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ullam perspiciatis illum excepturi repudiandae aperiam incidunt.",
    custom: {
      size1: "XS",
      size2: "S",
      size3: "M",
      size4: "L",
      size5: "XL",
    },
    reviews: {
      stars: 4.8,
    },
    qty:0,
  },
];
// localStorage.setItem("products", JSON.stringify(productTrendingMiniDB))